### ISSUE TITLE
Information

### ISSUE THREAD

**Issue by pandevim** [ManishTolani/Jigsaw-Puzzle#1]
Can I get a some details of this code/program
Also A README.me file would be appreciated

**Comment by ManishTolani** [comment]
And may I know why do you want it ?

**Comment by pandevim** [comment]
I would like to contribute to it. Because GitHub is all about contribution isn't it?
I'm formerly a LPU student and think you are/were too.

**Comment by ManishTolani** [comment]
Done !!

**Comment by pandevim** [comment]
Appreciated.
